"""Runs each algorithm on the same inputs used in SortingTest.py / BubbleSortTest.py
and writes comparison_count_report.md. Kept separate from SortingTest.py so that
the supplied test file is never altered, per the assignment's instructions.
"""
from Sorting import Sorting

RESULTS = []


def record(algorithm, original_array, sorting):
    RESULTS.append({
        "algorithm": algorithm,
        "input": list(original_array),
        "output": list(sorting.sorting_array),
        "comparison_count": sorting.comparison_count,
    })


def run_insertion_sort(input_array):
    original = list(input_array)
    sorting = Sorting(list(input_array))
    sorting.insertion_sort()
    record("insertion_sort", original, sorting)


def run_merge_sort(input_array):
    original = list(input_array)
    sorting = Sorting(list(input_array))
    if len(input_array) > 0:
        sorting.merge_sort(0, len(input_array) - 1)
    record("merge_sort", original, sorting)


def run_heap_sort(input_array):
    original = list(input_array)
    sorting = Sorting(list(input_array))
    sorting.heap_sort()
    record("heap_sort", original, sorting)


def run_bubble_sort(input_array):
    original = list(input_array)
    sorting = Sorting(list(input_array))
    sorting.bubble_sort()
    record("bubble_sort", original, sorting)


def run_bubble_sort_early_termination(input_array):
    original = list(input_array)
    sorting = Sorting(list(input_array))
    sorting.bubble_sort_early_termination()
    record("bubble_sort_early_termination", original, sorting)


def main():
    # Same inputs as the official SortingTest.py cases, plus the assignment's
    # required edge cases (empty, one-element, duplicates, negatives,
    # already-sorted, reverse-sorted) and the BubbleSortTest.py cases.
    published_cases = [[3, 6, 1], [1, 2, 3, 4]]
    edge_cases = [
        [],
        [5],
        [5, 5, 5, 5],
        [-3, -1, -7, 0, 2],
        [1, 2, 3, 4, 5],
        [5, 4, 3, 2, 1],
    ]

    for case in published_cases + edge_cases:
        run_insertion_sort(case)
        run_merge_sort(case)
        run_heap_sort(case)

    for case in [[3, 6, 1], [1, 2, 3, 4], [4, 3, 2, 1]] + edge_cases:
        run_bubble_sort(case)
        run_bubble_sort_early_termination(case)

    lines = [
        "# Comparison count report",
        "",
        "Generated by `generate_comparison_report.py` (run it again after any change",
        "to Sorting.py to refresh this file). Each row is one algorithm call: the",
        "input array, the array it produced, and the number of key comparisons",
        "(`comparison_count`) it performed.",
        "",
        "| Algorithm | Input | Output | Comparison count |",
        "|---|---|---|---|",
    ]
    for r in RESULTS:
        lines.append(
            f"| {r['algorithm']} | {r['input']} | {r['output']} | {r['comparison_count']} |"
        )
    with open("comparison_count_report.md", "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote comparison_count_report.md ({len(RESULTS)} runs)")


if __name__ == "__main__":
    main()
